apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - l2-addresspool
  # Optionally specify which nodes can announce
  # nodeSelectors:
  #   - matchLabels:
  #       kubernetes.io/hostname: ubuntu
