apiVersion: v2
name: istio
description: Istio service mesh chart with base and istiod components
type: application
version: 0.1.0
appVersion: "1.21.0"

dependencies:
  - name: base
    version: 1.21.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.21.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: 1.21.0
    repository: https://istio-release.storage.googleapis.com/charts
